# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'

- task: Docker@2
  displayName: 'docker build'
  inputs:
    repository: 'daveftech/aspnetcore-docker-image'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: 'docker push'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'daveftech/aspnetcore-docker-image'
    command: 'push'

    